### ISSUE TITLE
Dev Meeting #01

### ISSUE THREAD

**Issue by izqui** [aragon/meetings#1]
Proposed structure for these meetings by @Smokyish. To be tested in this first meeting.

#### Participants
- @harshjv 
- @readevalprint 
- @luisivan
- @izqui facilitator
- @Smokyish to handle recording, live streaming and collection of questions by viewers
#### Agenda
- Accounting app progress (@readevalprint)
- Overall v0.4 refactor state and scoping of the v0.4 deliverable (@izqui)
- Review of this week sprint https://github.com/orgs/aragon/projects/1 (@izqui)
- Meta: opinions on sprint organization (@everyone except @izqui)
- v0.5 planning (@harshjv)
- Versioning protocol https://github.com/aragon/aragon/issues/19 (@luisivan)
- v0.5 web3 providers. uPort & Ledger integration? Remove Metamask? (@izqui)
- What is everyone's focus/goals for next week (@everyone gets to talk)
- Other questions, comments or concerns by participants.
- Questions, comments or concerns by live viewers.
- Closing meeting

**Comment by Smokyish** [comment]
I think we can use the URL https://www.youtube.com/c/AragonProject for all Meeting streams.

**Comment by luisivan** [comment]
@izqui I'd like to talk about the Versioning Protocol a little bit

**Comment by izqui** [comment]
@luisivan added it to the agenda
@Smokyish i think it is better to paste in the link for the video once we have it, as it will be the same as the recorded url

**Comment by Smokyish** [comment]
Closing this since the Meeting was already held.
